### ISSUE TITLE
[BUG]: GET /user returns 404

### ISSUE THREAD

**Issue by GavinMasterson** [datawookie/clockify#16]
### Description of the bug

**Note: I am not the owner of the Clockify workspace that I am querying.**

I have an active clockify API key with which I can query workspaces, projects, and clients.
Unfortunately I cannot access user specific time entries because the first part of the request i.e. GET /user, returns a 404 error.

Here is a screenshot of my reprex test: 
![image](https://user-images.githubusercontent.com/51508128/196530387-9e4ea730-9a93-4b1e-a882-a999e68a20c4.png)
![image](https://user-images.githubusercontent.com/51508128/196531369-6964503a-c074-4278-b7cc-c2db3b8fb426.png)

### Steps To Reproduce

```
library(clockify)
library(logger)

log_threshold(DEBUG)

Sys.getenv("CLOCKIFY_API_KEY") |> set_api_key()

fathom <- workspaces()
workspace("5ef46294df73063139f60bfc")
my_projects <- projects() 
clients <- clients()
user()
users()
time_entries()
```

### Additional Information

Windows / WSL (Ubuntu)
VS Code
R 4.2.1 'Funny-Looking Kid'

**Comment by datawookie** [comment]
Hi @GavinMasterson,

Thanks for bringing this to my attention.

Firstly, these endpoints work fine for me locally. So there is clearly something different in our two setups. Just to get us aligned can you please:

1. Ensure that you are using the latest development version of the project? Please install from the `dev` branch.
2. Can you please create your own workspace and see if the problem persists there.
3. Share your API key with me (don't post it in the issue though!) so that I can dig deeper.

Let's get this sorted because you certainly should be able to retrieve details for at least your own user!

Thanks, Andrew.

PS. I suspect that you are not working with the current version from GitHub because of a slight difference in the debug log information that arose from a change a couple of months ago. These logs should now include the full path. For example:

```
DEBUG [2022-10-19 04:57:42] GET https://api.clockify.me/api/v1/workspaces/5ef46294df73063139f60bfc/users
```

Who said that logging isn't useful? :)

**Comment by GavinMasterson** [comment]
Hi @datawookie 

I have installed from the `dev` branch and updated all dependencies and the `users()` and `user()` functions work now. 

![image](https://user-images.githubusercontent.com/51508128/196710420-a2f25c5b-1363-40e9-9bbd-e0a13869fe8b.png)

Thanks.

**Comment by datawookie** [comment]
Awesome! It feels like I need to push an update to CRAN!
